GET http://localhost:3000

### FETCH ALL SONGS
GET http://localhost:3000/songs?limit=2&page=2

### FETCH SONG BY ID
GET http://localhost:3000/songs/2

### CREATE A NEW SONG
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "Welocme princess of hell",
    "artists": [1, 2],
    "releaseDate": "1984-09-29",
    "duration": "05:15",
    "lyrics": "Do not break the oath"
}

### UPDATE A SONG
PUT http://localhost:3000/songs/7
Content-Type: application/json

{
    "releasedDate": "1984-09-30"
}

### DELETE SONG BY ID
DELETE http://localhost:3000/songs/3

### CREATE A PLAYLIST
POST http://localhost:3000/playlists
Content-Type: application/json

{
    "name": "My fav",
    "songs": [4, 8],
    "user": 1
}

### SIGN UP USER
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "Barbed",
    "lastName": "Wire",
    "email": "ibrave@yandex.com",
    "password": "testpass"
}

### SIGN IN USER
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "ibrave@yandex.com",
    "password": "testpass"
}